### PR TITLE
Fix null pointer dereference in core1 UI controller code

### LINKED ISSUE #174: ZuluIDE does not initialise itself after cold boot.
A couple of times (not always) I saw with 2025.01.21-release that it locks for some time POST and starts flashing with a couple of slow signals and fast signals in loop. Then the system starts, but the CDROM is not present. Attaching a log collected from the SD card when I disabled computer after these "SOS" signals.

It is definitely something new, I don't recall it to fail that frequently with older non-experimental firmware revisions that I used.

[zululog.txt](https://github.com/user-attachments/files/18544369/zululog.txt)

System setup is the same: VIA Apollo 133A, Secondary slave ZuluIDE (the only device on the channel).

### PR DESCRIPTION
**Pull request by PetteriAimonen**
It seems sometimes core1 would have enough time to access uiStatusController which is null before the zuluide_setup() runs to stop it.

@hoffman373 Just a ping in case you want to check whether I have missed anything. It seems like a simple race condition between `zuluide_main_loop1()` accessing `uiStatusController` when it is null, vs. `zuluide_setup()` running `multicore_reset_core1()`.

Fixes #174

### CODE REVIEW

File: lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp [hunk 1]
```diff
@@ -316,8 +316,8 @@ uint8_t platform_check_for_controller()
 void platform_set_status_controller(zuluide::ObserverTransfer<zuluide::status::SystemStatus> *statusController) {
   logmsg("Initialized platform controller with the status controller.");
   display.init(&g_wire);
+  statusController->AddObserver(processStatusUpdate);
```
Comment (hoffman373) [inline lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp:319]: Out of curiosity, does this change have a different behavior than the previous version. I'm totally fine with it, but it seems to me like the net effect is the same. Am I missing something or is it a style/preference thing?

File: lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp [hunk 2]
```diff
@@ -1073,13 +1073,16 @@ void zuluide_main_loop1(void)
 {
     platform_poll_input();
 
-    // Process status update, if any exist.
-    if (!uiStatusController->ProcessUpdate()) {
-      // If no updates happend, refresh the display (enables animation)
-      display.Refresh();
-    }
+    if (uiStatusController)
```
Comment (hoffman373) [inline lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp:1076]: The check is safer. It nags at me that we have to do one more if branch in every iteration of the polling loop when it only is needed the first time. However I can't come up with a way of preventing the null reference without a check either.

**Comment by hoffman373** [comment]
I am fine with the merge. My questions are just discussions, not meant to prevent merging the code.

File: lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp (hunk 2 above)
Comment (PetteriAimonen) [reply lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp:1076]: Fortunately because `uiStatusController` pointer has to be loaded to a register anyway, the branch is only 1 instruction :)

File: lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp (hunk 1 above)
Comment (PetteriAimonen) [reply lib/ZuluIDE_platform_RP2040/ZuluIDE_platform.cpp:319]: I felt it might be risky to call `AddObserver()` after the second core already has access to it.
